name: Security Checks
on: [push]

jobs:
  test:
    name: OWASP ZAP SCANS
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       - name: Building Docker Node-Goat Image
         run: |
           sudo apt update -y
           sudo apt install docker-compose -y
           docker-compose build
       - name: Launching the app
         run: docker-compose up --detach

       - name: OWASP ZAP
         uses: zaproxy/action-baseline@v0.4.0
         with:
           # Target URL
           target: "http://localhost:4000"
           fail_action: false
           token: $
           issue_title: Security Tests
