name: Security Checks
on: [push]

jobs:
  test:
    name: OWASP ZAP SCANS
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       - name: Building Docker Node-Goat Image
         run: |
            sudo apt update -y
            sudo apt install docker-compose
            docker-compose build

       - name: Launching the app
         run: docker-compose up --detach

       - name: OWASP ZAP
         uses: zaproxy/action-full-scan@v0.10.0 
         with:
            target: 'http://localhost:4200' #Specify the endpoint of your application
            allow_issue_writing: false
